spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active:
      - development
  config:
    import:
      - "configtree:./"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: alasso.cda@gmail.com
    password: "vkdfuvquvumhvdlp"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: "smtp.gmail.com"
